"""empty message

Revision ID: 21c587284906
Revises: 2cc741bde28b
Create Date: 2023-04-29 12:09:09.753443

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '21c587284906'
down_revision = '2cc741bde28b'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('master_data',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('lookup_col', sa.Boolean(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('master_data')
    # ### end Alembic commands ###
