"""empty message

Revision ID: c0cf8af96514
Revises: 21c587284906
Create Date: 2023-06-29 19:04:01.140849

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision = 'c0cf8af96514'
down_revision = '21c587284906'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('dim_coin',
    sa.Column('id', sa.BIGINT(), autoincrement=True, nullable=False),
    sa.Column('coin_symbol', sa.VARCHAR(length=64), nullable=False),
    sa.Column('coin_name', sa.VARCHAR(length=512), nullable=False),
    sa.Column('checksum', sa.VARCHAR(length=512), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('fact_price',
    sa.Column('id', sa.BIGINT(), autoincrement=True, nullable=False),
    sa.Column('date', sa.TIMESTAMP(), nullable=False),
    sa.Column('coin_id', sa.BIGINT(), nullable=False),
    sa.Column('price', sa.DOUBLE(), nullable=True),
    sa.Column('checksum', sa.VARCHAR(length=512), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.drop_table('master_data')
    op.drop_table('crypto')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('crypto',
    sa.Column('id', sa.INTEGER(), autoincrement=True, nullable=False),
    sa.Column('is_btc', sa.BOOLEAN(), autoincrement=False, nullable=False),
    sa.Column('description', sa.VARCHAR(), autoincrement=False, nullable=False),
    sa.Column('my_date', postgresql.TIMESTAMP(), autoincrement=False, nullable=True),
    sa.PrimaryKeyConstraint('id', name='crypto_pkey')
    )
    op.create_table('master_data',
    sa.Column('id', sa.INTEGER(), autoincrement=True, nullable=False),
    sa.Column('lookup_col', sa.BOOLEAN(), autoincrement=False, nullable=False),
    sa.PrimaryKeyConstraint('id', name='master_data_pkey')
    )
    op.drop_table('fact_price')
    op.drop_table('dim_coin')
    # ### end Alembic commands ###
