volumes:
  crypto-vol:
  crypto-test-vol:

services:

  pgsql:
    image: postgres:12.11
    restart: always
    environment:
      POSTGRES_PASSWORD: pwd
      POSTGRES_USER: usr
      POSTGRES_DB: crypto
    volumes:
      - crypto-vol:/var/lib/postgresql/data
    ports:
      - 5432:5432

  pgsql-test:
    build: 
      context: .
      dockerfile: ./docker/postgres.test.Dockerfile
    restart: always
    environment:
      POSTGRES_PASSWORD: pwd 
      POSTGRES_USER: usr
      POSTGRES_DB: crypto
    volumes:
      - crypto-test-vol:/var/lib/postgresql/data
    ports:
      - 5433:5433

  pgadmin:
    image: dpage/pgadmin4:6.11
    restart: unless-stopped
    environment:
      PGADMIN_DEFAULT_PASSWORD: pwd
      PGADMIN_DEFAULT_EMAIL: test@test.com
      PGADMIN_LISTEN_PORT: 8080
    ports:
      - 8080:8080
    depends_on:
      - pgsql

  python:
    build: 
      context: .
      dockerfile: ./docker/python.Dockerfile
    depends_on:
      - pgsql
    ports:
      - 80:5000
    volumes:
      - ./app:/usr/src/app
