"""empty message

Revision ID: c968ce13dafb
Revises: 9c303e481bd0
Create Date: 2023-06-30 20:21:36.864187

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision = 'c968ce13dafb'
down_revision = '9c303e481bd0'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('dim_coin',
    sa.Column('id', sa.BIGINT(), autoincrement=True, nullable=False),
    sa.Column('coin_symbol', sa.VARCHAR(length=64), nullable=False),
    sa.Column('coin_name', sa.VARCHAR(length=512), nullable=False),
    sa.Column('checksum', sa.VARCHAR(length=512), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('fact_price',
    sa.Column('id', sa.BIGINT(), autoincrement=True, nullable=False),
    sa.Column('date', sa.TIMESTAMP(), nullable=False),
    sa.Column('coin_id', sa.BIGINT(), nullable=False),
    sa.Column('price', sa.DECIMAL(precision=5, scale=5), nullable=True),
    sa.Column('checksum', sa.VARCHAR(length=512), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.drop_table('crypto')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('crypto',
    sa.Column('id', sa.INTEGER(), autoincrement=True, nullable=False),
    sa.Column('is_btc', sa.BOOLEAN(), autoincrement=False, nullable=False),
    sa.Column('description', sa.VARCHAR(), autoincrement=False, nullable=False),
    sa.Column('my_date', postgresql.TIMESTAMP(), autoincrement=False, nullable=True),
    sa.PrimaryKeyConstraint('id', name='crypto_pkey')
    )
    op.drop_table('fact_price')
    op.drop_table('dim_coin')
    # ### end Alembic commands ###
